apiVersion: v1
kind: Service
metadata:
  name: learning-kube-httpd-service
spec:
  selector:
    app: learning-kube-httpd
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
  type: NodePort